adding alacritty themes + mac changes

diff --git a/bin/lfrun b/bin/lfrun
--- a/bin/lfrun
+++ b/bin/lfrun
@@ -9,11 +9,11 @@ cleanup() {
 if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
 	lf "$@"
 else
-	[ ! -d "$HOME/.cache/lf" ] && mkdir --parents "$HOME/.cache/lf"
-	export FIFO_UEBERZUG="$HOME/.cache/lf/ueberzug-$$"
-	mkfifo "$FIFO_UEBERZUG"
-	ueberzug layer -s <"$FIFO_UEBERZUG" -p json &
-	exec 3>"$FIFO_UEBERZUG"
-	trap cleanup EXIT
+	# [ ! -d "$HOME/.cache/lf" ] && mkdir -p "$HOME/.cache/lf"
+	# export FIFO_UEBERZUG="$HOME/.cache/lf/ueberzug-$$"
+	# mkfifo "$FIFO_UEBERZUG"
+	# ueberzug layer -s <"$FIFO_UEBERZUG" -p json &
+	# exec 3>"$FIFO_UEBERZUG"
+	# trap cleanup EXIT
 	lf "$@" 3>&-
 fi
